'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GameEngineTest1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bkMaze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bkMaze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Climbing1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Climbing1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Climbing2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Climbing2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Climbing3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Climbing3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Climbing4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Climbing4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Climbing5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Climbing5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Climbing6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Climbing6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Climbing7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Climbing7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClimbingShooting1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClimbingShooting1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crouching1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crouching1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crouching2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crouching2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crouching3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crouching3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crouching4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crouching4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crouching5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crouching5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crouching6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crouching6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crouching7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crouching7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Diving1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Diving1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Diving2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Diving2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DivingShooting1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DivingShooting1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DivingShooting2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DivingShooting2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FullBody1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FullBody1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hanging1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hanging1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hanging2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hanging2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hanging3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hanging3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hanging4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hanging4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hanging5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hanging5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HangingShooting1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HangingShooting1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HangingShooting2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HangingShooting2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HangingShooting3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HangingShooting3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HangingShooting4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HangingShooting4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HangingShooting5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HangingShooting5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hurt1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hurt1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hurt10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hurt10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hurt11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hurt11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hurt2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hurt2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hurt3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hurt3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hurt4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hurt4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hurt5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hurt5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hurt6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hurt6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hurt7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hurt7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hurt8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hurt8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hurt9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hurt9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jumping1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jumping1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jumping2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jumping2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jumping3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jumping3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jumping4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jumping4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jumping5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jumping5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JumpingShooting1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JumpingShooting1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JumpingShooting2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JumpingShooting2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JumpingShooting3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JumpingShooting3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JumpingShooting4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JumpingShooting4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JumpingShooting5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JumpingShooting5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Landing1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Landing1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Landing2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Landing2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LandingShooting1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LandingShooting1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LandingShooting2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LandingShooting2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Header:
        '''Dimensions: X, Y
        '''Tileset File Index: #
        '''Map Data: ...
        '''
        '''Tile Types:
        '''00: Air
        '''01: Basic Ground
        '''02: Spikes [Not Implemented Yet!].
        '''</summary>
        Friend ReadOnly Property MapFileDocumentation() As String
            Get
                Return ResourceManager.GetString("MapFileDocumentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MazeBlock1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MazeBlock1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MazeBlock2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MazeBlock2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MazeCeilingBlockLayerA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MazeCeilingBlockLayerA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MazeCeilingBlockLayerB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MazeCeilingBlockLayerB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MazeFloorBlockLayerA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MazeFloorBlockLayerA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MazeFloorBlockLayerB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MazeFloorBlockLayerB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MazeFloorBlockSlopeRightA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MazeFloorBlockSlopeRightA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MazeFloorBlockSlopeRightB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MazeFloorBlockSlopeRightB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MazeFloorSlopeRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MazeFloorSlopeRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property megamanx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("megamanx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property megamanx___Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("megamanx___Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mugshot1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mugshot1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Portrait1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Portrait1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PrtMaze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrtMaze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Running1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Running1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Running10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Running10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Running11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Running11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Running2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Running2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Running3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Running3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Running4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Running4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Running5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Running5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Running6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Running6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Running7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Running7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Running8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Running8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Running9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Running9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RunningShooting1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunningShooting1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RunningShooting10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunningShooting10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RunningShooting2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunningShooting2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RunningShooting3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunningShooting3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RunningShooting4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunningShooting4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RunningShooting5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunningShooting5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RunningShooting6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunningShooting6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RunningShooting7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunningShooting7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RunningShooting8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunningShooting8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RunningShooting9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunningShooting9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shot1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shot1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Standing1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Standing1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Standing2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Standing2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Standing3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Standing3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StandingShooting1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StandingShooting1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StandingShooting2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StandingShooting2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VictoryPose1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VictoryPose1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VictoryPose2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VictoryPose2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VictoryPose3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VictoryPose3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VictoryPose4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VictoryPose4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VictoryPose5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VictoryPose5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WarpIn1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WarpIn1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WarpIn2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WarpIn2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WarpIn3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WarpIn3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WarpIn4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WarpIn4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WarpIn5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WarpIn5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WarpIn6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WarpIn6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WarpIn7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WarpIn7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
